### ISSUE TITLE
[Meta] Upgrade client from `elastic-app-search` to `elastic-enterprise-search`

### ISSUE THREAD

**Issue by andsel** [logstash-plugins/logstash-integration-elastic_enterprise_search#13]
`elastic_enterprise_search` integration plugin is using the [`elastic-app-search`](https://github.com/elastic/app-search-ruby) client which is now deprecated. The client to use is [`elastic-enterprise-search`](https://github.com/elastic/enterprise-search-ruby), problem that arise is that the old client permitted to connect to AppSearch SaaS simply passing the parameter `:host_identifier` , which represents the host for the engine, like `host-2376rb` while the new client doesn't accept it and is intended to be used only to connect to Elastic Enterprise Search , both on-premise or SaaS, providing the full connection URL which bring the parameter name of `:host`.

### The problem
Existing Logstash installations that uses `logstash-integration-elastic_enterprise_search` up to version `2.1.2` permit to connect both to Swiftype SaaS AppSearch and ElasticEnterpriseSearch. If a user configure the [`host`](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elastic_app_search.html#plugins-outputs-elastic_app_search-host) setting it goes for SaaS Swiftype else if [`url`](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elastic_app_search.html#plugins-outputs-elastic_app_search-url) and [`path`](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elastic_app_search.html#plugins-outputs-elastic_app_search-path) are specified is can connect to on-premise or to Elastic Enterprise SaaS.

Switching to the new client, the plugin must provide the same functionality as before, permitting to configurations containing `host` setting to continue to work.

### Implementation
The idea is to use both clients, switching to one or the other based on which plugin options are contained in the pipeline definition.
If a user has defined `host` then connect to Swiftype's AppSearch SaaS using the old client `elastic-app-search`, for all the other cases use the new client `elastic-enterprise-search`.

### Tasks
- [x] If both `host` and `url` are provided, the plugin fails to register: "Error message telling the user that `host` is only using when using app search in Swiftype, and `url` only works for Elastic Enterprise Search".  
_Was already present, fixed error message with commit_ 2fa377c7066563612bfeee000033b26b308821bc
- [x] DOC: Clarify `host` and `path` only applies to Swiftype and add a couple examples of configuration about how to use it with Elasticsearch/Elastic Cloud vs Swiftype.
- [x] use `host` setting to automatically sends to Swiftype's SaaS (so use old client). _Done with_ 6d70b83473716758d4d830fdb1e04c4f2eabb610
- [x] use`url` setting to sends to Elastic Enterprise Search (so use new client). _Done with_ 6d70b83473716758d4d830fdb1e04c4f2eabb610
- [x] Unit Test: setting `host` would only ensure we use the old client. _Done with_ a4e420d35648ea2037f766ede76714af9182640a
- [x] Integration Test: setting `url` would continue to work as it does now, using the NEW client. Do not add a integration test for old behavior. _Test already present_
- [x] Deprecation warning about `host` setting saying "this will go away when Swiftype app search service is shutdown". Only when using this setting. _Done with commit_ 2d943e51988cd0b856b08db7435ff66d06ffec25

**Comment by andsel** [comment]
PR #3 implements all of this and  released with `2.2.0`
